---
info:
  title: Geppetto
  description: Geppetto - Virtual machine and infrastructure orchestration
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/geppetto
  x-cortex-tag: geppetto
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: metasploit
  x-cortex-groups:
  - exposure:internal-ship
openapi: 3.0.1
servers:
- url: "/"
